### ISSUE TITLE
[Coc Coc] Pop-under ads in https://animevi.net/one-piece-dao-hai-tac_7_Tap_940_Vietsub.html

### ISSUE THREAD

**Issue by hangtt1** [abpvn/abpvn#411]
1) Steps:
- Go to https://animevi.net/one-piece-dao-hai-tac_7_Tap_940_Vietsub.html.
- Tap to play video
2) Actual: Show pop-under ads
3) Expect: Can play video without pop-under ads

https://user-images.githubusercontent.com/85873327/174250281-a10a9061-ef7f-40a2-ba64-452d01317f2a.mp4

Note: We'd got feedback from users that they failed to play video in some links from this https://animevi.net/ and we disabled ||nessainy.net^$popup in ABP Easy List. Now, they could play some videos, however, pop-under ads still show

**Comment by hoang-rio** [comment]
I reported video can not play when use hydrax embed. But disable `||nessainy.net^$popup` is not is good solution because it is only solution can block popup on hydrax embed source.
Reason make video can not play able is not  `||nessainy.net^$popup` rule. It come from the way CC block it. With another extention popup will be open then close automaticaly then video can play normaly. Please tell your dev team about this

**Comment by hoang-rio** [comment]
@hangtt1 I tell you about solution and we will not update anything in ABPVN List about this issue so i close it right now. In you or you team need more information feel free to contact me.
