### ISSUE TITLE
ABP blocks top banner ads, show large blank space on site: saostar.vn

### ISSUE THREAD

**Issue by nguyenminhkhmt** [abpvn/abpvn#512]
**Ads description**

**Step to reproduce**
1. Go to website
2. Observe the site

**Website url**
saostar.vn

**Screenshot**
![IMG_7046](https://user-images.githubusercontent.com/16470510/218836853-a7b6b94a-a45d-4d3c-bb92-14fb51c973eb.PNG)

**Environment**
Browser: CocCoc iOS
Browser Version: Lastest version from the Appstore
Extensions/Adblocker Programs: ABP
Adblocker Version: Latest version
Subscription Filter: EasyList (minified) + ABPVN List (minified) + CocCoc strict rule

**Comment by hoang-rio** [comment]
This issue can not be fixed with ABP engine because ABP engine does not support stylesheet rule which method make this placeholder appear.

I created a fix for Ublock Origin and Adguard.

Here is the issue of ABP engine about still not support css rule https://gitlab.com/eyeo/adblockplus/abc/adblockpluscore/-/issues/210

**Comment by nguyenminhkhmt** [comment]
Okay, I got it. I'll report to our QA team. Thank u.
